### ISSUE TITLE
文件夹大小

### ISSUE THREAD

**Issue by Wangbicong** [ChestnutHeng/Wudao-dict#1]
总文件夹压缩前263M，为什么这么大。

**Comment by Wangbicong** [comment]
我看到dict.zip比较大。这个是本地的词典包吗？那其他空间呢？

**Comment by ChestnutHeng** [comment]
dict.zip大概有64M, 解压后的词典文件大概200M, 加起来就有263M了, 但是你可以删除dict.zip
解压后的词典没有优化, 所以很大

**Comment by Wangbicong** [comment]
你之前那个好用的 *.sh文件是哪个阿。并不需要这么大一个工程。。

**Comment by ChestnutHeng** [comment]
那个部分网页会格式错误, 有道网页改变了也会出问题,我就离线了一份词典

现在有个单文件的wd_monofile.py ,  只有15k, 你可以拷过去用
