### ISSUE TITLE
恒总求加新特性！

### ISSUE THREAD

**Issue by Easonzero** [ChestnutHeng/Wudao-dict#11]
能不能加一个英文单词缩写查询，以及缩写查询原英文单词的特性QAQ

**Comment by ChestnutHeng** [comment]
打开-o的在线选项应该可以查询~ 
以后我会添加缩写词表，这个比较难

**Comment by ChestnutHeng** [comment]
已经加了 @Easonzero ，只要有网，clone个新的试用一下？
