### ISSUE TITLE
在线查询网络释义

### ISSUE THREAD

**Issue by pzhang5** [ChestnutHeng/Wudao-dict#12]
有些词在线查询查不到，但是在网易的网页版是能查到网络释义的。不知能否考虑在在线查询中加入此释义？

**Comment by louisun** [comment]
欢迎使用  [iSearch](https://github.com/louisun/iSearch)

**Comment by ChestnutHeng** [comment]
什么词呢？举个例子

**Comment by ChestnutHeng** [comment]
已经可以保证和网页版一致，欢迎提出有问题的词
