### ISSUE TITLE
模糊查询的支持

### ISSUE THREAD

**Issue by lafiezh** [ChestnutHeng/Wudao-dict#15]
**模糊查询**对于查单词来说太重要了，往往记不住的话wd也发挥不出来功用啊啊。
建议起码包括以下几项：
- 单复数能够正常查询
- 只输入前半部，后边可以使用Tab补全或者列出候选项之类的

**Comment by ChestnutHeng** [comment]
这个建议不错，后续开发

**Comment by ChestnutHeng** [comment]
tab补全，大部分词的单复数已经支持，欢迎更新
