### ISSUE TITLE
建议默认只看释义

### ISSUE THREAD

**Issue by YHYJ** [ChestnutHeng/Wudao-dict#18]
基本上是查查看某个单词什么意思，例句什么的可以加参数查看，否则像我改成了默认【wd】是【wd -s】的效果，再想看例句就不知道加什么参数了

**Comment by ChestnutHeng** [comment]
这个默认是为了把例句的功能暴露给用户的
我可以再加个参数屏蔽，或者做成切换的模式哈

**Comment by YHYJ** [comment]
只看释义是最基本的功能，显示例句是增加功能，这样看应该默认显示释义，加参数显示例句，可以在-h里提示怎样显示例句啊【只是个建议】

**Comment by YHYJ** [comment]
哎，这样参数切换也不错呢

**Comment by ChestnutHeng** [comment]
切换模式已经支持，请git pull origin master体验！
