### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by witthong** [ChestnutHeng/Wudao-dict#19]
系统： Ubuntu 17.10

`Wudao-dict git:(master) ✗ sudo ./wudao-dict/setup.sh
cp: 无法获取'wd_com' 的文件状态(stat): 没有那个文件或目录
./wudao-dict/setup.sh: 行 23: /etc/bash_completion.d/wd: 没有那个文件或目录
Setup Finished! 
use wd [OPTION]... [WORD] to query the word.
自动补全会在下次打开命令行时启用
或者手动运行 source ~/.bashrc
`
`➜  ~ wd
/usr/bin/wd: 行 4: ./wdd: 没有那个文件或目录
`
单文件可以运行
`➜  ~ ./Downloads/Wudao-dict/wd_monofile task
task
英 [tɑːsk]  美 [tæsk]
vt. 分派任务
n. 工作，作业；任务
CET4 TEM4  ( tasking, tasked, tasks )
`

**Comment by ChestnutHeng** [comment]
请按照安装说明切目录哈
cd ./wudao-dict/wudao-dict
sudo bash setup.sh #或者sudo ./setup.sh
