### ISSUE TITLE
Very, very small problems

### ISSUE THREAD

**Issue by chengsluo** [ChestnutHeng/Wudao-dict#2]
First,Thank you!
------------
安装环境: 需要python3和bs4 (在线搜索用)

sudo apt-get install python3
sudo apt-get install python3-pip
pip3 install bs4

need change to:

sudo apt-get install python3
sudo apt-get install python3-pip
sudo pip3 install bs4

**Comment by ChestnutHeng** [comment]
Yes, you are right ! I have fixed it in latest commit.
