### ISSUE TITLE
能否将词组独立存入词组文件

### ISSUE THREAD

**Issue by eigeneko** [ChestnutHeng/Wudao-dict#20]
希望将查询的词组保存到单独的文件
不和生词本文件中的生词放到一起

**Comment by ChestnutHeng** [comment]
这个需求比较个人化哦，加个选项来指定生词本如何？

**Comment by Akitoki** [comment]
在配置文件中指定地址，查词的时候多一个参数就直接保存到不同生词本这样可以吗
