### ISSUE TITLE
无法在线查询

### ISSUE THREAD

**Issue by zhigui2222** [ChestnutHeng/Wudao-dict#24]
系统：Archlinux
桌面：kde
终端：Konsole
错误信息：
  File "WudaoCommand.py", line 135, in <module>
    main()
  File "WudaoCommand.py", line 131, in main
    app.query()
  File "WudaoCommand.py", line 103, in query
    word_info = get_text(self.word)
  File "/home/lkf/gitrepo/wudao_dict/wudao-dict/src/WudaoOnline.py", line 87, in get_text
    d = root.select(".wordGroup.def")
TypeError: 'NoneType' object is not callable
注：已安装bs4,lxml。
       控制台python
                   >>>import bs4
                    >>>import lvml
        也没有问题。

**Comment by ChestnutHeng** [comment]
发一下你查询的命令哈

**Comment by zhigui2222** [comment]
wd comput

**Comment by caleb072350** [comment]
我今天也遇到了类似的问题，搞了半天，后来发现并非不能在线查询，而是如果查的词输错或是太生僻，wd没有找到，它就会返回
Word not found, auto Online search...
No Internet : Please check your connection or try again.
这个错误。比如您这个问题，如果查询wd compute，就会返回正常的翻译，因为没有comput这个词，所以报错，不知道有没有解决您的问题
