### ISSUE TITLE
建议加个-v，否则不知道自己当前用的是哪个版本

### ISSUE THREAD

**Issue by YHYJ** [ChestnutHeng/Wudao-dict#25]
RT

**Comment by the-eric-kwok** [comment]
你可以用`git log`，看第一行的开头七个字符，和github的[commit](https://github.com/ChestnutHeng/Wudao-dict/commits/master)对比，如`8184201`

**Comment by ChestnutHeng** [comment]
版本查看已经支持，请git pull origin master体验！

**Comment by YHYJ** [comment]
多谢！
