### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ailionx** [ChestnutHeng/Wudao-dict#38]
It's really a fantastic tool. Would be great if it can add macOS support. Thanks.

**Comment by JasonHan0929** [comment]
跪求mac版

**Comment by chengsluo** [comment]
I have already submitted a Pull Request
[macOS support PR](https://github.com/ChestnutHeng/Wudao-dict/pull/43)

**Comment by freestyledash** [comment]
> I have already submitted a Pull Request
> [macOS support PR](https://github.com/ChestnutHeng/Wudao-dict/pull/43)

无法安装运行
```
sudo ./setup.sh
cp: /usr/bin/wd: Operation not permitted
chmod: /usr/bin/wd: No such file or directory
cp: /etc/bash_completion.d/wd: No such file or directory
./setup.sh: line 23: /etc/bash_completion.d/wd: No such file or directory
Setup Finished!
use wd [OPTION]... [WORD] to query the word.
自动补全会在下次打开命令行时启用
或者手动运行 source ~/.bashrc

```

**Comment by chengsluo** [comment]
> > I have already submitted a Pull Request
> > [macOS support PR](https://github.com/ChestnutHeng/Wudao-dict/pull/43)
> 
> 无法安装运行
> 
> ```
> sudo ./setup.sh
> cp: /usr/bin/wd: Operation not permitted
> chmod: /usr/bin/wd: No such file or directory
> cp: /etc/bash_completion.d/wd: No such file or directory
> ./setup.sh: line 23: /etc/bash_completion.d/wd: No such file or directory
> Setup Finished!
> use wd [OPTION]... [WORD] to query the word.
> 自动补全会在下次打开命令行时启用
> 或者手动运行 source ~/.bashrc
> ```

This Pull Request has not been merged yet
you need clone this:
```
git clone https://github.com/chengsluo/Wudao-dict
```
---
Pull Request 还没有被合并，所以ReadMe里面的git地址需要换成我fork的地址:
```
git clone https://github.com/chengsluo/Wudao-dict
```
其他的操作和ReadMe里面一样。

**Comment by ChestnutHeng** [comment]
thank you, this PR has been merged.
