### ISSUE TITLE
关于安装脚本的/usr/bin/wd脚本生成

### ISSUE THREAD

**Issue by ZmfCn** [ChestnutHeng/Wudao-dict#39]
1. 应该可以在wd脚本中保存一下安装路径，然后按照安装路径调用，要修改wdd文件应该可以避免在wd命令中跳转目录了。
2. 可以最后传给管道（more,less) 分屏，如：wdd $* | more，这个确实很需要，我是本地再写了一个脚本调用命令调用wdd的

**Comment by TYZRPVX** [comment]
wsl欢迎你

**Comment by ZmfCn** [comment]
不好意思，作者，我弄错了
