### ISSUE TITLE
建议: 用 sqlite3 来储存 dict/en.z, dict/zh.z 里的数据． Migrate the data in "dict/en.z", "dict/zh.z" to a sqlite3 database

### ISSUE THREAD

**Issue by Kienyew** [ChestnutHeng/Wudao-dict#41]
由于无道词典的操作方式是开启一个本地服务器 (WudaoServer.py) 随时聆听请求并以 json 格式返回查询单词的语意, 而服务器包含一个 JsonReader (src/JsonReader.py) 物体, 该物体储存了所有中英文单词的索引, 难免有些占用内存 (如图 约 116MB). 

![image](https://user-images.githubusercontent.com/31496021/47952146-ecc91880-dfa5-11e8-95af-5744ae3c4db1.png)

如果能够讲运用 Python 自带的 sqlite3 建立一个简单的数据库, 必能优化以上问题, 且能有效的加快查询速度.

**Comment by ChestnutHeng** [comment]
开发的时候试过sqlite3，效果不太理想，内存占得少，硬盘占得多
