### ISSUE TITLE
安全问题！

### ISSUE THREAD

**Issue by ailionx** [ChestnutHeng/Wudao-dict#46]
里面太多的http了，很多都可以用https的。我在互联网安全公司工作，安全分析师刚刚给我看我查的每一个词在公司网络上都看得到。现在全公司都知道我英语不好了！泪...
而且代码里有把在线查到的词上传到你的服务器数据库是吗？这至少应该提前说一声啊。这也是隐私保护的一部分。最好应该可以选择愿不愿意上传，而不是只要用了这个工具就上传给你。

**Comment by ChestnutHeng** [comment]
收集词库有两个原因：
1. 为了扩展离线词典的查询命中率，目前有1/4的查词无法在离线词典找到
2. 缩减词典体积
上传的词条只收集了词条本身，不关注用户，当然大家可以把这个上报文件注释掉~代码都在那里

**Comment by ailionx** [comment]
> 收集词库有两个原因：
> 
> 1. 为了扩展离线词典的查询命中率，目前有1/4的查词无法在离线词典找到
> 2. 缩减词典体积
>    上传的词条只收集了词条本身，不关注用户，当然大家可以把这个上报文件注释掉~代码都在那里

好的，如果能把里面的http能改成https的都改过去那就更好了。非常感谢这个项目。

**Comment by ChestnutHeng** [comment]
已经升级到https。请git pull origin master体验
