### ISSUE TITLE
git clone 总是到42%以后，就安装失败了

### ISSUE THREAD

**Issue by Soar-Sir** [ChestnutHeng/Wudao-dict#50]
大家看看有没有这种情况的发生

` 
✘ soar@sir  ~/Applications  git clone https://github.com/chestnutheng/wudao-dict
Cloning into 'wudao-dict'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
`

**Comment by icy1900** [comment]
git clone --depth 1 https://github.com/chestnutheng/wudao-dict

**Comment by pokitpeng** [comment]
我挂代理下就好了

**Comment by Soar-Sir** [comment]
> 我挂代理下就好了

好的,已解决
