### ISSUE TITLE
window 版本的能玩吗？或者window要怎么改造？

### ISSUE THREAD

**Issue by Mhunter132** [ChestnutHeng/Wudao-dict#57]

**Comment by Mhunter132** [comment]
![image](https://user-images.githubusercontent.com/46363359/78417952-11796200-766a-11ea-9487-c60fb7424a32.png)

**Comment by xiaoyan94** [comment]
Windows上可以在高级功能里面打开Linux子系统使用哈

**Comment by Mhunter132** [comment]
i had mounted it on my ubuntu of wsl that is awesome useful and convenient , voices out&nbsp; and recommend it to my friends


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaoyan94"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 晚上7:45
收件人:&nbsp;"ChestnutHeng/Wudao-dict"<Wudao-dict@noreply.github.com&gt;;
抄送:&nbsp;"张士明"<zxc741208584@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChestnutHeng/Wudao-dict] window 版本的能玩吗？或者window要怎么改造？ (#57)





 
Windows上可以在高级功能里面打开Linux子系统使用哈

**Comment by ChestnutHeng** [comment]
thanks for your support

**Comment by Freed-Wu** [comment]
You can port it to <https://github.com/msys2/MINGW-packages>, refer <https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-beautifulsoup4/PKGBUILD>

**Comment by somiceast** [comment]
这是来自QQ邮箱的休眠期自动回复邮件。你好，我最近正在休眠中，无法亲自回复你的邮件。我将在休眠期结束后，尽快给你回复。
