### ISSUE TITLE
如何更换字体颜色

### ISSUE THREAD

**Issue by evansan** [ChestnutHeng/Wudao-dict#7]
想把蓝色的翻译结果换成黄色

**Comment by ChestnutHeng** [comment]
Wudao-dict/wudao-dict/src/CommandDraw.py
27行，BLUE_PATTERN 换成 BROWN_PATTERN

还有以下可以选，或者自己加新的颜色。
RED_PATTERN = '\033[31m%s\033[0m'
GREEN_PATTERN = '\033[32m%s\033[0m'
BLUE_PATTERN = '\033[34m%s\033[0m'
PEP_PATTERN = '\033[36m%s\033[0m'
BROWN_PATTERN = '\033[33m%s\033[0m'
