### ISSUE TITLE
能否翻译长句？

### ISSUE THREAD

**Issue by qq774724635** [ChestnutHeng/Wudao-dict#79]
您好，wudao-dict的开源使用使我受益匪浅，不过我想问一下，wudao-dict是否支持长句翻译，目前支持吗？如果支持的话我应该怎么使用呢？

**Comment by somiceast** [comment]
这是来自QQ邮箱的休眠期自动回复邮件。你好，我最近正在休眠中，无法亲自回复你的邮件。我将在休眠期结束后，尽快给你回复。

**Comment by ChestnutHeng** [comment]
不支持翻译。wudao定位轻量级词典，可以搜搜命令行谷歌翻译的api

**Comment by somiceast** [comment]
这是来自QQ邮箱的休眠期自动回复邮件。你好，我最近正在休眠中，无法亲自回复你的邮件。我将在休眠期结束后，尽快给你回复。
