### ISSUE TITLE
有没有web based版本？

### ISSUE THREAD

**Issue by WanpengQian** [ChestnutHeng/Wudao-dict#8]
比如通过浏览器访问下面的URL
```
http://URL/querydict?example
```
然后在浏览器上显示英文单词example的解释。

**Comment by ChestnutHeng** [comment]
你可以使用有道的web版本：
http://dict.youdao.com/search?q=example

**Comment by ChestnutHeng** [comment]
你可以使用有道的web版本：
http://dict.youdao.com/search?q=example
